let a = "aa,li";
let b = "khan";
let c = 10;
// console.log(a.charAt(2));
// console.log(a.charCodeAt(0));
// console.log(a.concat(b));
// console.log(a.endsWith("i"));
// console.log(a.includes("x"));
// console.log(a.indexOf("i"));
// console.log(a.localeCompare(b));
// console.log(a.match("a"));
// console.log(a.repeat(6));
// console.log(a.replace("aa", "a"));
// console.log(a.search("a"));
// console.log(a.slice(0, 3));
// console.log(a.split(","));
// console.log(a.startsWith("a"));
// console.log(a.substr(0, 2));
// console.log(a.substring(0, 2));
// console.log(a.toLocaleLowerCase());
// console.log(a.toLocaleUpperCase());
// console.log(a.toString());
// console.log(a.toUpperCase());
// console.log(a.toLowerCase());
// console.log(a.toUpperCase());
// console.log(a.valueOf());
// console.log(a.trim());
// console.log(a.trimEnd());
// console.log(a.trimStart());
// console.log(a.padEnd(20, "a"));
// console.log(a.padStart(20, "a"));
